import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col'>
        <nav className='flex h-12 gap-10 border-2 border-solid border-white'>
          <Link href='/' scroll>
            Home
          </Link>
          <Link href='/about'>About Me</Link>
          <Link href='/'>Skills</Link>
          <Link href='/'>Work</Link>
          <Link href='/projects'>Projects</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
